# server.py — Q-SENSE Final Decryption Backend (AES-CBC compatible with AESLib)
from flask import Flask, jsonify, send_from_directory, request, abort
import requests, os, re
from binascii import unhexlify
from Crypto.Cipher import AES
from config import *
from quantum_key import get_quantum_challenge

# --- Locate frontend folder robustly ---
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
FRONTEND_FOLDER = os.path.join(BASE_DIR, "frontend")
if not os.path.exists(FRONTEND_FOLDER):
    FRONTEND_FOLDER = BASE_DIR

app = Flask(__name__, static_folder=FRONTEND_FOLDER, static_url_path="")

# ---------- AES-CBC Decryption ----------
def aes_decrypt_and_clean(cipher_hex: str, key_hex: str):
    """
    Decrypt AES-CBC data generated by Arduino AESLib (CBC, PKCS7, hex IV).
    Extract sensor value before ::challenge::quantum.
    """
    out = {"ok": False, "value": "N/A", "quantum": None, "error": None}
    try:
        if ":" not in cipher_hex:
            out["error"] = "invalid_format"
            return out

        iv_hex, ct_hex = cipher_hex.split(":", 1)
        iv = unhexlify(iv_hex)
        ct = unhexlify(ct_hex)
        key = unhexlify(key_hex)

        cipher = AES.new(key, AES.MODE_CBC, iv)
        pt = cipher.decrypt(ct)

        # PKCS7 unpad
        pad_len = pt[-1]
        if 1 <= pad_len <= AES.block_size:
            pt = pt[:-pad_len]

        # Decode plaintext safely
        raw_text = pt.decode("latin-1", errors="ignore").strip()

        # Expected format: value::challenge_id::quantum_hex
        parts = raw_text.split("::")
        if len(parts) >= 3:
            value = parts[0].strip()
            quantum = parts[-1].strip()
        else:
            # fallback: maybe challenge missing
            value = re.sub(r'[^0-9A-Za-z./-]', '', raw_text)
            quantum = None

        out["value"] = value if value else "N/A"
        out["quantum"] = quantum
        out["ok"] = True
        return out

    except Exception as e:
        out["error"] = str(e)
        return out


# --- Fetch latest ThingSpeak feed ---
def fetch_thingspeak_latest():
    url = f"https://api.thingspeak.com/channels/{THINGSPEAK_CHANNEL_ID}/feeds.json"
    params = {"api_key": THINGSPEAK_READ_KEY, "results": 1}
    r = requests.get(url, params=params, timeout=10)
    r.raise_for_status()
    return r.json()


# --- Quantum key generator ---
@app.route("/quantum", methods=["GET"])
def api_quantum():
    token = request.args.get("token")
    if token != ESP_AUTH_TOKEN:
        abort(401)
    n = int(request.args.get("n", 16))
    q_hex = get_quantum_challenge(n)
    return jsonify({"ok": True, "quantum_hex": q_hex})


# --- Main API: decrypt ThingSpeak latest feed ---
@app.route("/api/latest", methods=["GET"])
def api_latest():
    if request.args.get("auth") != ESP_AUTH_TOKEN:
        abort(401)

    try:
        data = fetch_thingspeak_latest()
    except Exception as e:
        return jsonify({"error": f"ThingSpeak fetch failed: {e}"}), 500

    feeds = data.get("feeds", [])
    if not feeds:
        return jsonify({"error": "No feed data"}), 404

    latest = feeds[-1]
    fields = {
        "field1": "Quantum Key",
        "field2": "Temperature",
        "field3": "Humidity",
        "field4": "IR Sensor",
        "field5": "MAX30100"
    }

    decrypted = {}
    for fkey, label in fields.items():
        raw = latest.get(fkey)
        if not raw:
            decrypted[label] = "N/A"
            continue

        parsed = aes_decrypt_and_clean(raw, SERVER_AES_KEY_HEX)
        if not parsed["ok"]:
            decrypted[label] = f"err:{parsed['error']}"
            continue

        # For Quantum Key: show the extracted quantum string
        if label == "Quantum Key":
            decrypted[label] = parsed["quantum"] or parsed["value"]
        else:
            decrypted[label] = parsed["value"]

    return jsonify({
        "ok": True,
        "decrypted": decrypted,
        "timestamp": latest.get("created_at")
    })


# --- Serve frontend ---
@app.route("/", defaults={"path": "index.html"})
@app.route("/<path:path>")
def serve_frontend(path):
    full_path = os.path.join(FRONTEND_FOLDER, path)
    if not os.path.exists(full_path):
        path = "index.html"
    return send_from_directory(FRONTEND_FOLDER, path)


# --- Run app ---
if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    print(f"✅ Q-SENSE running at http://127.0.0.1:{port}")
    print(f"📁 Serving frontend from: {FRONTEND_FOLDER}")
    app.run(host="0.0.0.0", port=port, debug=True)
